alawar_benchmark_homepage:
    path:     /insert/{iter}
    defaults: { _controller: AlawarBenchmarkBundle:Default:insert }

alawar_benchmark_select:
    path:     /select/{iter}
    defaults: { _controller: AlawarBenchmarkBundle:Default:select }
