parameters:
#    alawar_benchmark.example.class: Alawar\BenchmarkBundle\Example

services:
#    alawar_benchmark.example:
#        class: %alawar_benchmark.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
